NEON_URL = "postgresql://dash_user:Wachofnñofy48@ep-small-fire-agsc86td-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require"

DB_HOST = "ep-small-fire-agsc86td-pooler.c-2.eu-central-1.aws.neon.tech"
DB_NAME = "neondb"
DB_USER = "dash_user"
DB_PASS = "Wachofnñofy48"
DB_SSLMODE = "require"
